# Generated by Django 4.2 on 2025-07-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_at_order_time',
            new_name='price_at_order',
        ),
    ]
